# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(to='main.User'),
        ),
    ]
